import os

def generate_coverage_inclusion_log():
    tree_file_path = "tree.txt"
    coverage_file_path = "coverage.txt"
    
    # 1. Non-executable infrastructure folders to skip completely
    infra_folders = {
        '.github', '.git', '.venv', 'venv', 'env', '__pycache__', 
        '.pytest_cache', 'legacy', 'docs', 'artifacts', '.vscode', 
        '.hypothesis', 'htmlcov', 'policies', 'alembic'
    }
    
    # 2. Track only actual executable Python source files
    target_extensions = ('.py',)
    
    # 3. Explicit files to exclude from the code coverage targets
    infra_files = {'analyze_repo.py', 'conftest.py'}
    
    include_list = []

    print("Analyzing repository structure for target source files... 🔍")
    
    with open(tree_file_path, "w", encoding="utf-8") as tree_file:
        for root, dirs, files in os.walk('.'):
            # Standardize paths across Windows, macOS, and Linux
            normalized_root = root.replace(os.sep, '/')
            parts = normalized_root.strip('/').split('/')
            
            # Keep massive autogenerated folders out of tree.txt to keep it readable
            if any(p in {'.venv', 'venv', 'env', '.git', '__pycache__', 'htmlcov'} for p in parts):
                continue
                
            level = len(parts) - 1 if parts != [''] else 0
            indent = '    ' * level
            folder_name = os.path.basename(root) or "Root"
            tree_file.write(f"{indent}📁 {folder_name}/\n")
            
            file_indent = '    ' * (level + 1)
            
            for file in files:
                tree_file.write(f"{file_indent}📄 {file}\n")
                relative_file_path = f"{normalized_root}/{file}".lstrip('./')
                
                # Check exclusion criteria
                is_infra_folder = any(inf in parts for inf in infra_folders)
                is_infra_file = file in infra_files or not file.endswith(target_extensions)
                
                # Exclude testing frameworks, helpers, and test blocks
                is_test_module = (
                    file.startswith('test_') or 
                    file.endswith('_test.py') or 
                    'tests' in parts or
                    'test_helpers' in parts or
                    any('test_' in part or 'track_' in part for part in parts)
                )
                
                # Exclude files starting with "term" (as per earlier requirement)
                starts_with_term = file.startswith('term')
                
                # IF it's clean source code, add it to our inclusion list
                if not (is_infra_folder or is_infra_file or is_test_module or starts_with_term):
                    include_list.append(relative_file_path)

    # Write the target source files directly to coverage.txt
    with open(coverage_file_path, "w", encoding="utf-8") as cov_file:
        for pattern in sorted(set(include_list)):
            cov_file.write(f"{pattern}\n")
            
    print(f"📊 Analysis complete! Generated logs based on your 1,000+ files:")
    print(f"   -> '{tree_file_path}' (Visual tree architecture map)")
    print(f"   -> '{coverage_file_path}' (Contains ONLY files that must be covered)")

if __name__ == "__main__":
    generate_coverage_inclusion_log()
